language: java
jdk:
- oraclejdk8
before_script:
- if [ ! -z "$TRAVIS_TAG" ]; then mvn versions:set -DnewVersion=$TRAVIS_TAG; fi
script:
- mvn clean install
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: 3MZ53faDcan65nZn4POhGZxKmGEDHi+vZ4RIWgwP7M99VSig45b6fkBMdpalcnMc906Q+YU1SumCXFTVsuCeQoPqs/JOoDaDbEKIrqN+jSH63Iq7SAbgHMDCYPif9t/tIvABa/KBi9HyQQCqEFPkf0zl5ODFzLO+IPdyjrAUnrihZTIgdfegzcfBL4uklng3V5VAYMq5DCZis0ahr5kMVkwkyYkl/lToRwcN/k29x78HT+9IlHnjyNg0aJt50gQHa1vlX9oWlfCDTBKiyhkYSPIXtj+y17/LLUxRpBo5dfGFwKPGEKfHvsMdt9urW11xrASqg+gCSJL65D7w1EVZpqmxhyXl6soOLHCbI0v5cZA05RlVCnrg7Ybak3TgmwdKVWYV319j817xVEsyKdWiwaSW3zdU8rtw3dSyVA9SIs1J4Y+tB/72cdeGnOgB1GHVfpQFz3pRVy+vsNVW+pf5VStO7HKUY7YnHVmZTbleEaGPFtgrXLkp87YitxFluqlWOFLN8ndNBX5hqUmPP5lcxvXMrMfbvoA5hKEevE8EdMz89O5DH2uIzbbLDgC2cnbN5Q8Osab+5uuBgqMD13DdmqepEi7VipTxaZDZld1lE8mB6Jwxa49YoxMQQsyGADc4EHThwy+u/1iv9UZK1+FgV6p1pHkmCTLu0az3Rln+tVw=
  file_glob: true
  file: "**/target/*.jar"
  skip_cleanup: true
  on:
    tags: true
