language: java
jdk:
- openjdk8
- oraclejdk8
addons:
  apt:
    packages:
    - libxml2-utils
before_script:
- PROJECT_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)
- if [ ! -z "$TRAVIS_TAG" ]; then mvn versions:set -DnewVersion=$TRAVIS_TAG; fi
script:
- mvn clean install
after_success:
- bash <(curl -s https://codecov.io/bash)
- if [[ "$PROJECT_VERSION" == *SNAPSHOT ]]; then mvn deploy -B -DskipTests=true --settings settings.xml; fi
deploy:
  provider: releases
  api_key:
    secure: 3MZ53faDcan65nZn4POhGZxKmGEDHi+vZ4RIWgwP7M99VSig45b6fkBMdpalcnMc906Q+YU1SumCXFTVsuCeQoPqs/JOoDaDbEKIrqN+jSH63Iq7SAbgHMDCYPif9t/tIvABa/KBi9HyQQCqEFPkf0zl5ODFzLO+IPdyjrAUnrihZTIgdfegzcfBL4uklng3V5VAYMq5DCZis0ahr5kMVkwkyYkl/lToRwcN/k29x78HT+9IlHnjyNg0aJt50gQHa1vlX9oWlfCDTBKiyhkYSPIXtj+y17/LLUxRpBo5dfGFwKPGEKfHvsMdt9urW11xrASqg+gCSJL65D7w1EVZpqmxhyXl6soOLHCbI0v5cZA05RlVCnrg7Ybak3TgmwdKVWYV319j817xVEsyKdWiwaSW3zdU8rtw3dSyVA9SIs1J4Y+tB/72cdeGnOgB1GHVfpQFz3pRVy+vsNVW+pf5VStO7HKUY7YnHVmZTbleEaGPFtgrXLkp87YitxFluqlWOFLN8ndNBX5hqUmPP5lcxvXMrMfbvoA5hKEevE8EdMz89O5DH2uIzbbLDgC2cnbN5Q8Osab+5uuBgqMD13DdmqepEi7VipTxaZDZld1lE8mB6Jwxa49YoxMQQsyGADc4EHThwy+u/1iv9UZK1+FgV6p1pHkmCTLu0az3Rln+tVw=
  file_glob: true
  file:
  - target/*.jar
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: pqKazQQ1NPKqNTsubb7S0Xx6B4UhNe15wkIiaITaHvRVZrg/BpnuEjiVNrG2hemfg76rXZssGM33DpPYQHbKh49mHTMimrIWou1RnKgZIc+XIH8zmz4IMlB9k5bo1cYvFTdVlhsatkEA7MJIiZBgWkss9FK1oX0Z1WNP7ZDsZOlI6H/PgP569guOFZLpjIXmrc/cSDvUjKhR1W9b0I8AXukBpbmatNsuqRehiZbCoJ8pquCbxu57gU0c5rND4dIMwo9lXNH8ccId7HrOFPIrvcKIVpE12Y+JS88qxW4E5Sy3TTB0NelZ7eWXT1DcYm5iaQg4ULENFLBlWalWxqzK2jklQZRUjGLaqik/yYHhLpAat5EwHjR0k6NbR610RPk1mT4CDQM0WKYbdWpoA39NkGHcF0p02Eo0RMH+qRizKbLLSOnyq5ZeETALl+hr6BkQ6fIAPL4zo7YIIBHSNI5qUEOTekCQRinKRZ9bAeW2eqivBivdwFYporfNdsH972N9Ojfv7VDH4d9Y3pCESjcQ5xxXv/G64x8yEPs1WfLz2n45lxMnsD+8FKsR6HeJX8C7VG3VBNcNVboKGk/9/fDuj4I/jlY+1hjYhA9bqyXdCLh4ba9TAkJMFlwRKkRigm2J9iWYbpRUCNtcUHhnFrvjv89kW66Rftu6mDqnq1oT8HU=
  - secure: COf9U19GFNH9v+EJt+7mH/G+133IbKXkzXdhQzmQpf7lJ6ZpPmShiLIX776UI9vWXiHFl64XtV6nfNgpdfiq727/eIuvVTw1eE2xhwbps+K7GtkEkDo1vX2/HZf89bLuDzCW9vtd0pCZA8w6mGM7NGlNi8BAllErsGEd4ASeFOwzOonxLA6yk/hVbDsNApykm7E3IYR2qJJ0lSUtq8aI3rA5QLQCDqBynGNdCfZZQuuY7aDp+hhHIZEY3BYJgm8NPmEEgvnbBm5wg2GYxxb/fo3ehUnzUoc+1X45N+NYOtChxG67LFM6ZqXO4jmJSbu26uto4T7pau4dsm1EpPeQibHgz7WbDvqFK6F6XUvU9d41uaemLOm3AByyEvDGcSqrqeUIdLpPjKXipxMc8/HWhRkcy98+9uOjJPu7nlXfDS3tKOo55TJ8xB2SEGizNIG2+8ebjx3k+m2FBLLNAYADTKXeKCiIagz567WFNPCczDAQqA3dVPXparINF9jVEmTFaw8SLC8qTQODnGZl39OOF58bs5J2Hg2zHS3Gi7VHXQuMBWmanuKy3FJxZ0xRrbGRMu4EcsPsTiXRCEiSuFD9FEbDeZ6CyY9pJmYXCu1HiVqguIn0VKAGzM+xjLy6qFKAMipXfZjpmuJXLtCQMRWovXV5b6ZMOZNiQP2D5PwqWMY=
